### ISSUE TITLE
Fix horizontal scroll

### ISSUE THREAD

**Issue by averrin** [xcv58/Tab-Manager-v2#1245] opened 2021-05-28 11:24 UTC
Im using your amazing extension in Vivaldi's web panel. It works well, unlike others tab managers. But there is a small glitch: horizontal scroll. Fix is easy: set overflow-x: hidden. Or something like that.

**Comment by xcv58** [comment] 2021-05-28 17:19
Thanks for the feedback @averrin!

Do you mean the horizontal scroll doesn't work on the https://vivaldi.com/ browser?

**Comment by xcv58** [comment] 2021-05-29 04:12
![image](https://user-images.githubusercontent.com/503123/120057631-57755000-bff9-11eb-85db-3302c5afac23.png)
I can't reproduce this in Vivaldi

**Comment by averrin** [comment] 2021-06-08 08:40
Sorry for long answer. I specifically said about "web panel". It isn't regular tab, its smaller docking window in left panel.
![image](https://user-images.githubusercontent.com/426007/121152850-dbbfa280-c845-11eb-91c5-5efcfb08ae47.png)
And it has a horizontal scroll in every panel width.

**Comment by xcv58** [comment] 2021-06-08 16:56
Got it, thanks. I will double-check in 1-2 days.

**Comment by xcv58** [comment] 2021-06-08 16:57
Confirmed I could reproduce the same issue, will have a fix shortly.

**Comment by xcv58** [comment] 2021-06-09 16:40
0b4695e5f336e106f5947d532751a1f776c44b78 the fix commit

**Comment by xcv58** [comment] 2021-06-11 04:14
@averrin it should be fixed in v1.15.2, could you please confirm?

**Closed** 2021-07-15 03:28 UTC
